from __future__ import annotations

INTENT_PLANNED = 'planned'
INTENT_BLOCKED = 'blocked'
INTENT_SUBMITTED_UNKNOWN = 'submitted_unknown'
INTENT_ACCEPTED_OPEN = 'accepted_open'
INTENT_REJECTED = 'rejected'
INTENT_EXPIRED_UNSUBMITTED = 'expired_unsubmitted'
INTENT_EXPIRED_UNCONFIRMED = 'expired_unconfirmed'
INTENT_SETTLED = 'settled'
INTENT_ORPHANED = 'orphaned'
INTENT_AMBIGUOUS = 'ambiguous'

BROKER_UNKNOWN = 'unknown'
BROKER_OPEN = 'open'
BROKER_CLOSED_WIN = 'closed_win'
BROKER_CLOSED_LOSS = 'closed_loss'
BROKER_CLOSED_REFUND = 'closed_refund'
BROKER_REJECTED = 'rejected'
BROKER_CANCELLED = 'cancelled'
BROKER_NOT_FOUND = 'not_found'

SETTLEMENT_WIN = 'win'
SETTLEMENT_LOSS = 'loss'
SETTLEMENT_REFUND = 'refund'

TRANSPORT_ACK = 'ack'
TRANSPORT_REJECT = 'reject'
TRANSPORT_TIMEOUT = 'timeout'
TRANSPORT_EXCEPTION = 'exception'
TRANSPORT_UNKNOWN = 'unknown'

EVENT_INTENT_CREATED = 'intent_created'
EVENT_INTENT_BLOCKED = 'intent_blocked'
EVENT_SUBMIT_REQUESTED = 'submit_requested'
EVENT_SUBMIT_ACKED = 'submit_acked'
EVENT_SUBMIT_REJECTED = 'submit_rejected'
EVENT_SUBMIT_TIMEOUT = 'submit_timeout'
EVENT_SUBMIT_EXCEPTION = 'submit_exception'
EVENT_RECONCILE_MATCHED = 'reconcile_matched'
EVENT_RECONCILE_ORPHAN = 'reconcile_orphan'
EVENT_ORDER_OPEN = 'order_open'
EVENT_ORDER_SETTLED = 'order_settled'
EVENT_ORDER_CANCELLED = 'order_cancelled'
EVENT_RECONCILE_AMBIGUOUS = 'reconcile_ambiguous'

CONSUMES_QUOTA_STATES = {
    INTENT_SUBMITTED_UNKNOWN,
    INTENT_ACCEPTED_OPEN,
    INTENT_SETTLED,
}

TERMINAL_INTENT_STATES = {
    INTENT_REJECTED,
    INTENT_EXPIRED_UNSUBMITTED,
    INTENT_EXPIRED_UNCONFIRMED,
    INTENT_SETTLED,
    INTENT_ORPHANED,
    INTENT_AMBIGUOUS,
}

PENDING_INTENT_STATES = {
    INTENT_PLANNED,
    INTENT_SUBMITTED_UNKNOWN,
    INTENT_ACCEPTED_OPEN,
}

TERMINAL_BROKER_STATES = {
    BROKER_CLOSED_WIN,
    BROKER_CLOSED_LOSS,
    BROKER_CLOSED_REFUND,
    BROKER_REJECTED,
    BROKER_CANCELLED,
    BROKER_NOT_FOUND,
}
