#!/usr/bin/env python
"""
P35d (v2) — Hard reset envutil to eliminate circular imports + ensure all env_* users import what they use.

Fixes:
- ImportError: cannot import name 'env_bool' from partially initialized module 'natbin.envutil'
- NameError: env_int is not defined (collect_recent.py, etc.)

Usage (from repo root):
  .\.venv\Scripts\python.exe .\scripts\patches\p35d_envutil_hard_reset_apply_v2.py
"""
from __future__ import annotations

import datetime as _dt
import os
import re
import sys
from pathlib import Path
import py_compile


ENVUTIL_TEXT = """# Auto-generated by scripts/patches/p35d_envutil_hard_reset_apply_v2.py
# IMPORTANT:
# - This module must stay stdlib-only.
# - Do NOT import natbin.* modules here (it will create circular imports).
from __future__ import annotations

import os
from typing import Any, Optional


_TRUE = {"1", "true", "t", "yes", "y", "on"}
_FALSE = {"0", "false", "f", "no", "n", "off"}


def _norm_num(s: str) -> str:
    s = s.strip()
    # pt-BR decimal comma support:
    # - if only comma exists: treat comma as decimal separator
    # - if both comma and dot: assume dot is decimal and commas are thousand separators
    if "," in s and "." not in s:
        return s.replace(",", ".")
    if "," in s and "." in s:
        return s.replace(",", "")
    return s


def to_str(v: Any, default: str = "") -> str:
    if v is None:
        return default
    return str(v)


def to_int(v: Any, default: int = 0) -> int:
    if v is None:
        return default
    if isinstance(v, bool):
        return int(v)
    if isinstance(v, int):
        return v
    s = to_str(v, "").strip()
    if s == "":
        return default
    try:
        return int(float(_norm_num(s)))
    except Exception:
        return default


def to_float(v: Any, default: float = 0.0) -> float:
    if v is None:
        return default
    if isinstance(v, (int, float)):
        return float(v)
    s = to_str(v, "").strip()
    if s == "":
        return default
    try:
        return float(_norm_num(s))
    except Exception:
        return default


def to_bool(v: Any, default: bool = False) -> bool:
    if v is None:
        return default
    if isinstance(v, bool):
        return v
    s = to_str(v, "").strip().lower()
    if s == "":
        return default
    if s in _TRUE:
        return True
    if s in _FALSE:
        return False
    return default


def env_str(key: str, default: str = "", *, allow_empty: bool = True) -> str:
    raw = os.getenv(key)
    if raw is None:
        return default
    if (not allow_empty) and (raw.strip() == ""):
        return default
    return raw


def env_int(key: str, default: Any = 0) -> int:
    raw = os.getenv(key)
    if raw is None:
        return to_int(default, 0)
    return to_int(raw, to_int(default, 0))


def env_float(key: str, default: Any = 0.0) -> float:
    raw = os.getenv(key)
    if raw is None:
        return to_float(default, 0.0)
    return to_float(raw, to_float(default, 0.0))


def env_bool(key: str, default: Any = False) -> bool:
    raw = os.getenv(key)
    if raw is None:
        return to_bool(default, False)
    return to_bool(raw, to_bool(default, False))
"""


ENV_FUNCS = ("env_float", "env_int", "env_bool", "env_str")


def _ts() -> str:
    return _dt.datetime.now().strftime("%Y%m%d_%H%M%S")


def find_repo_root(start: Path) -> Path:
    p = start.resolve()
    for _ in range(10):
        if (p / "src" / "natbin").exists():
            return p
        if p.parent == p:
            break
        p = p.parent
    raise SystemExit("Could not find repo root (expected src/natbin). Run this from inside the repo.")


def backup(path: Path) -> Path:
    b = path.with_suffix(path.suffix + f".bak_{_ts()}")
    b.write_bytes(path.read_bytes())
    return b


def write_envutil(repo: Path) -> None:
    target = repo / "src" / "natbin" / "envutil.py"
    if target.exists():
        b = backup(target)
        print(f"[P35d] backup envutil: {b}")
    target.write_text(ENVUTIL_TEXT, encoding="utf-8", newline="\n")
    print(f"[P35d] wrote envutil: {target}")


def _detect_used_env_funcs(text: str) -> set[str]:
    used = set()
    for name in ENV_FUNCS:
        if re.search(rf"\\b{name}\\b", text):
            used.add(name)
    return used


def _insert_import_block(text: str, names: list[str]) -> str:
    # Insert after module docstring and any __future__ imports
    lines = text.splitlines(True)

    # Find insertion point: after shebang/encoding + docstring + future imports.
    i = 0
    # shebang / encoding
    if i < len(lines) and lines[i].startswith("#!"):
        i += 1
    if i < len(lines) and re.match(r"#.*coding[:=]", lines[i]):
        i += 1

    # docstring (triple quotes)
    if i < len(lines) and re.match(r"\\s*[uUrR]?['\\\"]{3}", lines[i]):
        quote = lines[i].lstrip()[0:3]
        i += 1
        while i < len(lines) and quote not in lines[i]:
            i += 1
        if i < len(lines):
            i += 1  # include closing docstring line

    # future imports
    while i < len(lines) and re.match(r"\\s*from\\s+__future__\\s+import\\s+", lines[i]):
        i += 1

    block = (
        "try:\\n"
        f"    from .envutil import {', '.join(names)}\\n"
        "except Exception:\\n"
        f"    from envutil import {', '.join(names)}\\n"
        "\\n"
    )
    return "".join(lines[:i]) + block + "".join(lines[i:])


def _ensure_imports_for_file(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    used = _detect_used_env_funcs(text)
    if not used:
        return False

    # envutil.py must remain stdlib-only. Never patch imports into it.
    if path.name == "envutil.py":
        return False

    # Already has a try/except envutil block?
    # We'll normalize it to include ALL used names.
    names = sorted(list(used))

    # Case A: from .envutil import ...
    m = re.search(r"^\\s*from\\s+\\.envutil\\s+import\\s+(.+)$", text, flags=re.M)
    if m:
        # Replace the whole import line with the needed names (plus keep stable ordering)
        text2 = re.sub(
            r"^\\s*from\\s+\\.envutil\\s+import\\s+(.+)$",
            "from .envutil import " + ", ".join(names),
            text,
            flags=re.M,
            count=1,
        )
        if text2 != text:
            path.write_text(text2, encoding="utf-8", newline="\\n")
            return True
        return False

    # Case B: from envutil import ...
    m = re.search(r"^\\s*from\\s+envutil\\s+import\\s+(.+)$", text, flags=re.M)
    if m:
        text2 = re.sub(
            r"^\\s*from\\s+envutil\\s+import\\s+(.+)$",
            "from envutil import " + ", ".join(names),
            text,
            flags=re.M,
            count=1,
        )
        if text2 != text:
            path.write_text(text2, encoding="utf-8", newline="\\n")
            return True
        return False

    # Case C: try/except block already present (very simple heuristic)
    if "from .envutil import" in text and "except" in text and "from envutil import" in text:
        # Replace both import lines inside the block
        text2 = re.sub(r"from\\s+\\.envutil\\s+import\\s+.*", "from .envutil import " + ", ".join(names), text, count=1)
        text2 = re.sub(r"from\\s+envutil\\s+import\\s+.*", "from envutil import " + ", ".join(names), text2, count=1)
        if text2 != text:
            path.write_text(text2, encoding="utf-8", newline="\\n")
            return True
        return False

    # Else insert a safe block
    text2 = _insert_import_block(text, names)
    if text2 != text:
        path.write_text(text2, encoding="utf-8", newline="\\n")
        return True
    return False


def patch_env_imports(repo: Path) -> int:
    base = repo / "src" / "natbin"
    changed = 0
    for p in sorted(base.rglob("*.py")):
        # skip backups and pycache
        if ".bak_" in p.name or p.parts[-1] == "__pycache__":
            continue
        try:
            if _ensure_imports_for_file(p):
                changed += 1
        except UnicodeDecodeError:
            continue
    print(f"[P35d] env import patched files: {changed}")
    return changed


def smoke_imports(repo: Path) -> None:
    # Ensure repo/src is first in sys.path
    src = str((repo / "src").resolve())
    if src not in sys.path:
        sys.path.insert(0, src)

    # Import envutil
    import importlib
    envutil = importlib.import_module("natbin.envutil")
    for fn in ENV_FUNCS:
        if not hasattr(envutil, fn):
            raise SystemExit(f"[P35d][FAIL] envutil missing {fn}")

    # Import gate_meta (this is where you were failing)
    importlib.import_module("natbin.gate_meta")
    print("[P35d] smoke imports OK (envutil + gate_meta)")


def compile_natbin(repo: Path) -> None:
    base = repo / "src" / "natbin"
    for p in sorted(base.rglob("*.py")):
        if ".bak_" in p.name:
            continue
        py_compile.compile(str(p), doraise=True)
    print("[P35d] py_compile OK for src/natbin/*.py")


def main() -> None:
    repo = find_repo_root(Path(__file__).resolve())
    print(f"[P35d] repo={repo}")
    write_envutil(repo)
    patch_env_imports(repo)

    # Smoke + compile
    smoke_imports(repo)
    compile_natbin(repo)

    print("[P35d] DONE. Next:")
    print("  - python scripts/tools/selfcheck_repo.py")
    print("  - pwsh -ExecutionPolicy Bypass -File scripts/scheduler/observe_loop_auto.ps1 -Once")


if __name__ == "__main__":
    main()
