# Originally generated by a legacy patch script (see git history).
# IMPORTANT:
# - This module must stay stdlib-only.
# - Do NOT import natbin.* modules here (it will create circular imports).
from __future__ import annotations

import os
from typing import Any, Optional


_TRUE = {"1", "true", "t", "yes", "y", "on"}
_FALSE = {"0", "false", "f", "no", "n", "off"}


def _norm_num(s: str) -> str:
    s = s.strip()
    # pt-BR decimal comma support:
    # - if only comma exists: treat comma as decimal separator
    # - if both comma and dot: assume dot is decimal and commas are thousand separators
    if "," in s and "." not in s:
        return s.replace(",", ".")
    if "," in s and "." in s:
        return s.replace(",", "")
    return s


def to_str(v: Any, default: str = "") -> str:
    if v is None:
        return default
    return str(v)


def to_int(v: Any, default: int = 0) -> int:
    if v is None:
        return default
    if isinstance(v, bool):
        return int(v)
    if isinstance(v, int):
        return v
    s = to_str(v, "").strip()
    if s == "":
        return default
    try:
        return int(float(_norm_num(s)))
    except Exception:
        return default


def to_float(v: Any, default: float = 0.0) -> float:
    if v is None:
        return default
    if isinstance(v, (int, float)):
        return float(v)
    s = to_str(v, "").strip()
    if s == "":
        return default
    try:
        return float(_norm_num(s))
    except Exception:
        return default


def to_bool(v: Any, default: bool = False) -> bool:
    if v is None:
        return default
    if isinstance(v, bool):
        return v
    s = to_str(v, "").strip().lower()
    if s == "":
        return default
    if s in _TRUE:
        return True
    if s in _FALSE:
        return False
    return default


def env_str(key: str, default: str = "", *, allow_empty: bool = True) -> str:
    raw = os.getenv(key)
    if raw is None:
        return default
    if (not allow_empty) and (raw.strip() == ""):
        return default
    return raw


def env_int(key: str, default: Any = 0) -> int:
    raw = os.getenv(key)
    if raw is None:
        return to_int(default, 0)
    return to_int(raw, to_int(default, 0))


def env_float(key: str, default: Any = 0.0) -> float:
    raw = os.getenv(key)
    if raw is None:
        return to_float(default, 0.0)
    return to_float(raw, to_float(default, 0.0))


def env_bool(key: str, default: Any = False) -> bool:
    raw = os.getenv(key)
    if raw is None:
        return to_bool(default, False)
    return to_bool(raw, to_bool(default, False))
